name: Build and Publish

on:
  #workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      # Checks-out repository
      - uses: actions/checkout@v1
        with:
            ref: refs/heads/main
            fetch-depth: 1
        
      # Execute psake build
      - run: |
          ./build.sh ci
          cd _publish
          ls
